steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/$PROJECT_ID/sims-frontend:$COMMIT_SHA', '.']

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/$PROJECT_ID/sims-frontend:$COMMIT_SHA']

images:
  - 'gcr.io/$PROJECT_ID/sims-frontend:$COMMIT_SHA'

substitutions:
  _COMMIT_SHA: $COMMIT_SHA
  _PROJECT_ID: szr-hackathon-sbx-5242
