steps:
  # Step 1: Build the Docker image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'europe-west4-docker.pkg.dev/$PROJECT_ID/sims-hackathon:$COMMIT_SHA', '.']
    dir: sims-frontend

  # Step 2: Push the Docker image to Google Container Registry
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'europe-west4-docker.pkg.dev/$PROJECT_ID/sims-hackathon:$COMMIT_SHA']
    dir: sims-frontend

images:
  - 'europe-west4-docker.pkg.dev/$PROJECT_ID/sims-hackathon:$COMMIT_SHA'

options:
  logging: CLOUD_LOGGING_ONLY

substitutions:
  _COMMIT_SHA: $COMMIT_SHA
  _PROJECT_ID: szr-hackathon-sbx-5242
